services:
  db:
    image: docker.io/library/mariadb:10.5
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    volumes:
      - "database_store:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: metaverse
      MYSQL_ROOT_PASSWORD: password

  metaverse:
    container_name: opensim
    build:
      context: ./build/latest
      dockerfile: Dockerfile.source
      args:
        - OPENSIM_VERSION=master
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
      - "9000:9000/udp"
    environment:
      DATABASE_ENGINE: mysql
      MYSQL_SERVER: db
      MYSQL_DATABASE: metaverse
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      ESTATE_OWNER_NAME: Governor Linden
      ESTATE_OWNER_PASSWORD: password

volumes:
  database_store:
