name: Build Container

on:
  push:
    branches:
    - main
    paths:
    - "opensim/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Container
      uses: docker/build-push-action@v2
      with:
        push: true
        context: "{{defaultContext}}:opensim"
        tags: soupbowl/opensimulator:edge,ghcr.io/soup-bowl/opensimulator-docker:edge
        platforms: linux/amd64,linux/arm64
