name: Build Beta Container

on:
  push:
    branches:
      - main
    paths:
      - "beta/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['alpine-beta']
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Login to ghcr.io
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Container
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:beta/${{ matrix.tag }}"
          tags: >
            soupbowl/opensimulator:${{ matrix.tag }},
            ghcr.io/soup-bowl/opensimulator-docker:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
